CREATE EXTENSION 'uuid-ossp';

CREATE TABLE users (
  id UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(), 
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role VARCHAR(20),
  created_at DATE
);

CREATE TABLE orders(
  id UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  customer_name TEXT,
  country TEXT,
  state TEXT,
  city TEXT,
  address TEXT,
  phone_number TEXT,
  email TEXT,
  brand TEXT,
  production_manager TEXT,
  sm_manager TEXT,
  items JSONB[],
  uploader TEXT,
  created_at DATE
);

CREATE TABLE options(
  id UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  type TEXT,
  value TEXT
);

INSERT INTO options (type, value) VALUES
  ('brands', 'WorkingGirlNG'),
  ('brands', 'ShirtRepublic'),
  ('brands', 'OfficePlug'),
  ('brands', 'OliviersCloset'),
  ('brands', 'Stylestation'),
  ('brands', 'Denimsng'),
  ('brands', 'KhadeejahNG'),
  ('brands', 'SKactive'),
  ('prodManagers', 'Aighangbe Tina'),
  ('prodManagers', 'Ogoh mercy chiwendu'),
  ('prodManagers', 'Joseph Agnes'),
  ('prodManagers', 'Ekine Kehinde'),
  ('prodManagers', 'Adebimpe'),
  ('prodManagers', 'Ajimoti Tunde'),
  ('smManagers', 'Adebimpe Aderemi'),
  ('smManagers', 'Onabanjo Azeezat Olamide'),
  ('smManagers', 'Vincent Theophilus'),
  ('smManagers', 'Helen Idokoe'),
  ('smManagers', 'Ajimoti Tunde'),
  ('items', 'Dress'),
  ('items', 'Top'),
  ('items', 'Skirt'),
  ('items', 'Pants'),
  ('items', 'Shorts'),
  ('items', 'Blazers'),
  ('items', 'Abaya'),
  ('items', 'Blazer and Pant'),
  ('items', 'Blazer and Skirt'),
  ('items', 'Top and Pant'),
  ('items', 'Top and Skirt'),
  ('itemsCost', '5000'),
  ('itemsCost', '6000'),
  ('itemsCost', '7000'),
  ('itemsCost', '7500'),
  ('itemsCost', '7800'),
  ('itemsCost', '8000'),
  ('itemsCost', '9000'),
  ('itemsCost', '10000'),
  ('itemsCost', '11000'),
  ('itemsCost', '12000'),
  ('itemsCost', '13000'),
  ('itemsCost', '14000'),
  ('itemsCost', '15000'),
  ('itemsCost', '16000'),
  ('itemsCost', '17000'),
  ('itemsCost', '18000'),
  ('itemsCost', '19000'),
  ('itemsCost', '20000'),
  ('itemsCost', '21000'),
  ('itemsCost', '22000'),
  ('itemsCost', '23000'),
  ('itemsCost', '24000'),
  ('itemsCost', '25000'),
  ('itemsCost', '26000'),
  ('itemsCost', '27000'),
  ('itemsCost', '28000'),
  ('itemsCost', '29000'),
  ('itemsCost', '30000'),
  ('cutters', 'Jhonson'),
  ('cutters', 'Friday'),
  ('cutters', 'Sarah'),
  ('cutters', 'Michael'),
  ('stitchers', 'Ibrahim'),
  ('stitchers', 'Usman'),
  ('stitchers', 'Abdul-Rahmon'),
  ('stitchers', 'Precious'),
  ('stitchers', 'Yinka'),
  ('stitchers', 'Olokodana'),
  ('stitchers', 'Anu'),
  ('stitchers', 'Iseoluwa'),
  ('stitchers', 'Michael'),
  ('stitchers', 'Janet'),
  ('stitchers', 'Suliyat'),
  ('stitchers', 'Kehinde'),
  ('stitchers', 'George'),
  ('stitchers', 'Elizabeth'),
  ('stitchers', 'Shade'),
  ('stitchers', 'Opeyemi Girl'),
  ('stitchers', 'Imole'),
  ('stitchers', 'Matthew'),
  ('stitchers', 'Eniola'),
  ('stitchers', 'Yetunde'),
  ('stitchers', 'Ahmed'),
  ('stitchers', 'Hawawu'),
  ('stitchers', 'Hannah'),
  ('stitchers', 'Mrs Nancy'),
  ('stitchers', 'Ramota'),
  ('stitchers', 'Deborah'),
  ('stitchers', 'Barakat'),
  ('stitchers', 'Mary'),
  ('stitchers', 'Fatimoh'),
  ('stitchers', 'Fatiu'),
  ('stitchers', 'Wumi2'),
  ('stitchers', 'Wole'),
  ('stitchers', 'Funmi'),
  ('stitchers', 'Abosede'),
  ('stitchers', 'Toyin'),
  ('stitchers', 'Opeyemi Boy'),
  ('stitchers', 'Ganiyat'),
  ('stitchers', 'Folashade'),
  ('cutCost', '100'),
  ('cutCost', '150'),
  ('cutCost', '200'),
  ('cutCost', '250'),
  ('tailoringFee', '400'),
  ('tailoringFee', '500'),
  ('tailoringFee', '600'),
  ('tailoringFee', '700'),
  ('tailoringFee', '800'),
  ('tailoringFee', '900'),
  ('tailoringFee', '1000'),
  ('tailoringFee', '1200'),
  ('tailoringFee', '1500'),
  ('tailoringFee', '2000'),
  ('tailoringFee', '2500'),
  ('tailoringFee', '3000');
